language: java
jdk: openjdk8
sudo: false
branches:
  only:
  - master
before_install:
- rm -r src/test
- git clone --depth 1 --branch test2019 git@github.com:kristofersTeaching/ssy066.git
- cp -r ssy066/src/test ./src/
- find . -type d | sed -e "s/[^-][^\/]*\//  |/g" -e "s/|\([^ ]\)/|-\1/"
script: mvn surefire-report:report
after_success:
- git checkout master
- mkdir Reports
- cp ./target/site/surefire-report.html ./Reports/
deploy:
  provider: releases
  api_key:
    secure: jMMeo+rfUXcn7WgCe1zB356R4eCaJImkvbq6XYWoC7ffOcE0L7WCZYCCZkIDNn9janBvx/Rvceub+YKwpm9Duw40Wyy5AuzskBGuWhrbz4ZZKodOQeHWOyxuQIP25JhTl0HpFnHFk6vMbZroSKv0SOcabjEkdHU7Nc1RuA90bsOIhB9Ms0qi0QY74Zf8mjdrUHPiiKnH7eQtGaTwXPPsD83iIquGnByqyfHOGBiYXEa00NQOrrVNzNTW8lcIV4mLoKtJ3QxbrAmcFGWPjOxw2bJjGB4jRIMSfGRvvrrVWYrBFfOf7DjMwhttYuNSU6LN/ayQ2YTUyGFnT/vUGVfThEzpqBv+Jyu8OHR9sk5LvcPaZ5eFx6ZPiAat23t64GYNjktFtZNViMXWVohC6rpb+lmYy4QTH7ceBCIGqrMuWpPiYDqf52DZrkyLomoftA4H2Wq1WO7AuurNO84tjesUmasF9a3kZFIm4H55+50dkzx7U32p18wXOtR3BkiGQ3ZHbcLwGkKK2nKAWrzZqMUB1TQjOvqR2UPc2ap+qALcJloLALvUkL/vtt9+9k2Yw0pE5+VKXeV6ZRDDQaAzDy+ZPeFfgJ+Qb+etGSc4to/bV/3ePxpcMVi4V4TPCqMIxolTLlUo6uSd2eCL9Qou8+R/p3EPob0t8RV2886JexfTxWA=
  file: "./Reports/surefire-report.html"
skip_cleanup: true